// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "46dda63e-05ad-4af6-a685-59794e2584b2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float humidity_cloud;
float temperature_cloud;
int light_cloud;
int moisture_cloud;
int water_level_cloud;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity_cloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature_cloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light_cloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture_cloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_level_cloud, READ, ON_CHANGE, NULL);

}
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
